import { useMemo, useState } from "react";
import { updateMerchantPassword } from "./api/merchantApi.js";

export default function MerchantResetPassword() {
  const token = useMemo(() => { const values = new URLSearchParams(window.location.hash.slice(1)); const value = values.get("type") === "recovery" ? values.get("access_token") : ""; if (value) window.history.replaceState({}, "", window.location.pathname); return value; }, []);
  const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [message, setMessage] = useState(""); const [done, setDone] = useState(false);
  async function submit(event) { event.preventDefault(); if (password !== confirm) { setMessage("Passwords do not match."); return; } try { await updateMerchantPassword(token, password); setDone(true); setMessage("Your password has been updated."); } catch (error) { setMessage(error.message || "This recovery link is invalid or has expired."); } }
  if (!token) return <main className="flex min-h-screen items-center justify-center bg-[#fbfaf7] px-6"><div className="max-w-md rounded-3xl bg-white p-8 text-center shadow-xl"><h1 className="text-3xl font-semibold">Reset link unavailable</h1><p className="mt-4 text-slate-600">This recovery link is invalid, expired or has already been used.</p><a href="/merchant/forgot-password" className="mt-6 inline-block font-semibold text-[#16856f]">Request a new link</a></div></main>;
  return <main className="flex min-h-screen items-center justify-center bg-[#fbfaf7] px-6"><div className="w-full max-w-md rounded-3xl bg-white p-8 shadow-xl"><h1 className="text-3xl font-semibold">Set a new password</h1>{done ? <><p className="mt-4 text-slate-600">{message}</p><a href="/merchant" className="mt-6 inline-block font-semibold text-[#16856f]">Continue to sign in</a></> : <form onSubmit={submit} className="mt-8 space-y-5"><input className="w-full rounded-xl border px-4 py-3" type="password" placeholder="New password" autoComplete="new-password" minLength={8} required value={password} onChange={(e)=>setPassword(e.target.value)} /><input className="w-full rounded-xl border px-4 py-3" type="password" placeholder="Confirm password" autoComplete="new-password" minLength={8} required value={confirm} onChange={(e)=>setConfirm(e.target.value)} />{message ? <p className="text-sm text-red-700">{message}</p> : null}<button className="w-full rounded-xl bg-[#143d3b] px-5 py-3 font-semibold text-white">Update password</button></form>}</div></main>;
}
