export const CRM_STAGES = ["new","contacted","interested","trial","customer","not_now","lost"];
export const CRM_ACTIVITY_TYPES = ["in_person_visit","email","phone_call","sms","instagram_dm","demo","note","trial_event"];
export function stageLabel(stage){return String(stage||"new").replaceAll("_"," ").replace(/\b\w/g,(v)=>v.toUpperCase());}
export function pocketStampState(account){if(!account?.merchant_id&&!account?.merchant?.id)return "Not configured";const state=account.pocketstamp_state||account.pocketStampState||{};const ready=[state.appleReady&&"Apple Ready",state.googleReady&&"Google Ready",state.assetsReady&&"Assets Ready"].filter(Boolean);return ready.length?ready.join(" · "):"Merchant linked";}
export function localDayKey(value){if(!value)return null;const d=value instanceof Date?value:new Date(value);if(Number.isNaN(d.valueOf()))return null;return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
export function followUpUrgency(value,now=new Date()){const key=localDayKey(value),today=localDayKey(now);if(!key)return "neutral";if(key===today)return "today";return key<today?"overdue":"neutral";}
export function crmListFilter(accounts,filter,now=new Date()){if(filter?.startsWith("date:"))return accounts.filter((a)=>localDayKey(a.next_follow_up_at)===filter.slice(5));if(filter==="active_prospects")return accounts.filter((a)=>!["customer","not_now","lost"].includes(a.stage));if(filter==="prospects")return accounts.filter((a)=>!a.merchant_id&&a.stage!=="customer");if(filter==="interested")return accounts.filter((a)=>a.stage==="interested");if(filter==="trials")return accounts.filter((a)=>a.stage==="trial");if(filter==="customers")return accounts.filter((a)=>a.stage==="customer");if(filter==="configured")return accounts.filter((a)=>a.merchant_id);if(filter==="follow_up")return accounts.filter((a)=>a.next_follow_up_at);if(filter==="due_today")return accounts.filter((a)=>followUpUrgency(a.next_follow_up_at,now)==="today");if(filter==="overdue")return accounts.filter((a)=>followUpUrgency(a.next_follow_up_at,now)==="overdue");return accounts;}
export function crmSearch(accounts,term){const query=String(term||"").trim().toLowerCase();if(!query)return accounts;return accounts.filter((a)=>[a.display_name,a.name,a.email,a.phone,a.address,a.locality,a.postcode,a.primary_contact?.name,a.primary_contact?.email,a.primary_contact?.phone,a.merchant?.slug,a.slug].some((v)=>String(v||"").toLowerCase().includes(query)));}
export function crmSort(accounts,sort){const [field,direction]=String(sort||"next_follow_up:asc").split(":"),factor=direction==="desc"?-1:1;const value=(a)=>{if(field==="name")return String(a.display_name||a.name||"").toLowerCase();if(field==="location")return String(a.locality||a.address||"").toLowerCase();if(field==="contact")return String(a.primary_contact?.name||"").toLowerCase();return a[field]||"";};return [...accounts].sort((a,b)=>{const av=value(a),bv=value(b);if(av===""&&bv!=="")return 1;if(bv===""&&av!=="")return -1;return av<bv?-factor:av>bv?factor:0;});}
export function pipelineCounts(accounts,archivedCount=0,now=new Date()){return {active_prospects:accounts.filter((a)=>!["customer","not_now","lost"].includes(a.stage)).length,interested:accounts.filter((a)=>a.stage==="interested").length,trials:accounts.filter((a)=>a.stage==="trial").length,customers:accounts.filter((a)=>a.stage==="customer").length,due_today:accounts.filter((a)=>followUpUrgency(a.next_follow_up_at,now)==="today").length,overdue:accounts.filter((a)=>followUpUrgency(a.next_follow_up_at,now)==="overdue").length,archived:archivedCount};}
export function calendarWeek(selectedDate){const selected=new Date(selectedDate),monday=new Date(selected.getFullYear(),selected.getMonth(),selected.getDate());monday.setDate(monday.getDate()-((monday.getDay()+6)%7));return Array.from({length:7},(_,index)=>{const day=new Date(monday);day.setDate(monday.getDate()+index);return day;});}
export function formatWeekRange(selectedDate){const days=calendarWeek(selectedDate),start=days[0],end=days[6],month=(date)=>new Intl.DateTimeFormat("en-GB",{month:"long"}).format(date),startDay=start.getDate(),endDay=end.getDate(),startYear=start.getFullYear(),endYear=end.getFullYear();if(startYear===endYear&&start.getMonth()===end.getMonth())return `${startDay}–${endDay} ${month(end)} ${endYear}`;if(startYear===endYear)return `${startDay} ${month(start)} – ${endDay} ${month(end)} ${endYear}`;return `${startDay} ${month(start)} ${startYear} – ${endDay} ${month(end)} ${endYear}`;}
export function calendarEntries(accounts){return accounts.reduce((map,account)=>{const key=localDayKey(account.next_follow_up_at);if(key){if(!map[key])map[key]=[];map[key].push(account);}return map;},{});}
export function activityIcon(type){return ({in_person_visit:"↗",email:"✉",phone_call:"☎",sms:"▣",instagram_dm:"◎",demo:"◇",trial_event:"★",follow_up_scheduled:"＋",follow_up_rescheduled:"↝",follow_up_completed:"✓",status_change:"→",note:"•"})[type]||"•";}
export function followUpTimelineDetails(activity){if(!String(activity?.activity_type||"").startsWith("follow_up_"))return null;const followUp=(activity.source_ref||activity.sourceRef||{}).follow_up||{};return {previousAt:followUp.previous_at||null,previousNote:followUp.previous_note||null,nextAt:followUp.next_at||null,nextNote:followUp.next_note||null};}
export function isArchived(account){return Boolean(account?.archived_at);}
export function hasTechnicalTabs(account){return Boolean(account?.merchant_id||account?.merchant?.id);}
export function crmListMessage({loading,error,total,visible}){if(loading)return "Loading CRM cafés…";if(error)return null;if(total===0)return "No CRM cafés are available.";if(visible===0)return "No CRM cafés match this view.";return null;}
export function distinctActivityNotes(summary,notes){const value=String(notes||"").trim();return value&&value!==String(summary||"").trim()?value:null;}
const REVIEW_ONLY_CONTEXTS=new Map([
  ["36619132f19bb72e0ab7c75b16f7b1ac206ab3a1fef2836e2d57ec49df01b305:IRL Outreach:30","Met Sadie (owner)."],
  ["36619132f19bb72e0ab7c75b16f7b1ac206ab3a1fef2836e2d57ec49df01b305:IRL Outreach:31","Met Harriet and Naomi (roles unconfirmed)."],
]);
function reviewContextKey(activity){const source=activity?.source_ref||activity?.sourceRef||{};return `${source.workbookSha256||""}:${source.sheet||""}:${source.row||""}`;}
export function decorateTimelineActivities(activities){const shown=new Set();return (activities||[]).map((activity)=>{const key=reviewContextKey(activity),reviewContext=REVIEW_ONLY_CONTEXTS.get(key)||null,showReviewContext=reviewContext&&!shown.has(key);if(showReviewContext)shown.add(key);return {...activity,displayNotes:distinctActivityNotes(activity.summary,activity.notes),reviewContext:showReviewContext?reviewContext:null};});}
export function assignedAdminLabel(account,adminContext){if(account?.assigned_admin?.full_name)return account.assigned_admin.full_name;if(account?.assigned_admin_user_id&&account.assigned_admin_user_id===adminContext?.id)return adminContext.fullName||adminContext.email||"Current admin";return account?.assigned_admin_user_id||"Unassigned";}
